set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TRIPLE "aarch64-linux-gnu")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)

set(CMAKE_C_COMPILER_TARGET ${TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${TRIPLE})
set(CMAKE_ASM_COMPILER_TARGET ${TRIPLE})

set(CMAKE_EXE_LINKER_FLAGS_INIT    "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")

set(CMAKE_AR      /usr/bin/aarch64-linux-gnu-ar      CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB  /usr/bin/aarch64-linux-gnu-ranlib  CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP   /usr/bin/aarch64-linux-gnu-strip   CACHE FILEPATH "Strip")
set(CMAKE_NM      /usr/bin/aarch64-linux-gnu-nm      CACHE FILEPATH "NM")
set(CMAKE_OBJCOPY /usr/bin/aarch64-linux-gnu-objcopy CACHE FILEPATH "Objcopy")
set(CMAKE_OBJDUMP /usr/bin/aarch64-linux-gnu-objdump CACHE FILEPATH "Objdump")

set(CMAKE_FIND_ROOT_PATH /usr/lib/aarch64-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
list(APPEND CMAKE_FIND_ROOT_PATH "${REPO_ROOT}/build/duckstation-deps")
set(DiscordRPC_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/DiscordRPC")
set(freetype_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/freetype")
set(harfbuzz_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/harfbuzz")
set(libjpeg-turbo_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/libjpeg-turbo")
set(libzip_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/libzip")
set(plutosvg_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/plutosvg")
set(libpng_DIR "${REPO_ROOT}/build/duckstation-deps/lib/libpng")
set(PNG_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/PNG")
set(SDL3_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/SDL3")
set(Shaderc_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/Shaderc")
set(SoundTouch_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/SoundTouch")
set(zstd_DIR "${REPO_ROOT}/build/duckstation-deps/lib/cmake/zstd")
set(cpuinfo_DIR "${REPO_ROOT}/build/duckstation-deps/share/cpuinfo")
set(spirv_cross_c_shared_DIR "${REPO_ROOT}/build/duckstation-deps/share/spirv_cross_c_shared/cmake")
set(WebP_DIR "${REPO_ROOT}/build/duckstation-deps/share/WebP/cmake")

set(CMAKE_C_FLAGS_RELEASE "-Ofast -DNDEBUG -flto=auto" CACHE STRING "C Release flags")
set(CMAKE_CXX_FLAGS_RELEASE "-Ofast -DNDEBUG -flto=auto" CACHE STRING "C++ Release flags")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=armv8-a" CACHE STRING "C flags")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a" CACHE STRING "C++ flags")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -flto=auto" CACHE STRING "Executable linker flags")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -flto=auto" CACHE STRING "Shared linker flags")

set(CMAKE_CROSSCOMPILING TRUE)
