#!/bin/sh
# MIMIKI - System initialization script

echo "MIMIKI starting..."

echo "Enabling deep sleep..."
echo deep > /sys/power/mem_sleep

echo "Loading kernel modules..."
depmod -a
echo "  Loading display driver..."
modprobe panel-generic-dsi || echo "Warning: Display driver failed to load"
echo "  Loading input driver..."
modprobe rocknix-singleadc-joypad || echo "Warning: Joypad driver failed to load"
echo "  Loading mali gpu driver..."
modprobe mali_kbase || echo "Warning: Mali GPU driver failed to load"

echo "Setting up audio..."
amixer -c 0 sset 'Master' unmute 65%
amixer -c 0 cset name='Playback Mux' SPK

if [ -b "/dev/mmcblk2p1" ]; then
    echo "Mounting second SD Card..."
    mount /dev/mmcblk2p1 /mnt/games2
    if [ $? -ne 0 ]; then
        echo "Failed to mount second SD Card! Make sure it's formatted as fat32 or exfat!"
    fi

    # Copy bios for user convenience in case they want to use the second card for all game files
    if [ -d "/mnt/games2/data" ]; then
        cp -r /mnt/games2/data/* /mnt/games/data/
    fi
    # Also check for the RA version folder scheme. Convenience!
    if [ -d "/mnt/games2/bios" ]; then
        cp -r /mnt/games2/bios/* /mnt/games/data/
        if [ -d "/mnt/games/bios/dc" ]; then
            mv /mnt/games/bios/dc/* /mnt/games/data/
            rmdir /mnt/games/bios/dc/
        fi
    fi
fi

cp /root/.ppsspp/ppsspp.ini /mnt/games/data/ppsspp/PSP/SYSTEM/
cp /root/.ppsspp/controls.ini /mnt/games/data/ppsspp/PSP/SYSTEM/

echo "==> MIMIKI init complete!"
